version: '3.8'

services:
  passwordless:
    image: extropysk/passwordless:latest
    ports:
      - 3000:3000
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - default

  mongo:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    networks:
      - default

volumes:
  mongo:
